name: Fenrispatch
version: '${project.version}'
main: fenrisfox86.fenrispatch.Fenrispatch
api-version: 1.19
authors: [ FenrisFox86 ]
description: FenrisFox86's custom patch for FenrisRPG SMP
softdepend: [ProtocolLib]
